version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    
    container_name: users-db
    
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
    
    ports:
      - "5332:5432"

    networks:
      - db
    
    restart: unless-stopped
    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U damian -d postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
      


networks:
  db:
    driver: bridge

volumes:
  db: