version: 1
disable_existing_loggers: False

logging:
  level: INFO
  handlers:
    file:
      enabled: true
      path: "logs"
      max_bytes: 10485760
      backup_count: 7
    console:
      enabled: true
      level: INFO
  format:

    console: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    file: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

    